# REST API

### Get All Profiles
### curl http://localhost:3000/profile
GET http://localhost:3000/profile

### Create New Profile
### curl -X POST http://localhost:3000/profile
POST http://localhost:3000/profile
Content-Type: application/json

{
    "username": "demo7",
    "password": "1234",
    "mobile": "0999999994",
    "cardId": "1234567890119"
}

### Get some profile by id
GET http://localhost:3000/profile/2b790e4e-9b41-46ee-8a11-a7ae866f0593

### Login
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "demo7",
    "password": "1234"
}

### Encode
POST http://localhost:3000/encode
Content-Type: application/json

{
    "username": "demo11",
    "password": "789456321",
    "mobile": "099955550",
    "cardId": "1211100908076"
}

### Decode
GET http://localhost:3000/decode/873c0731-cfae-4e4d-a918-d87d652f43f9
Content-Type: application/json

